#ifndef PARMOON__REPOSITORY_INFO
#define PARMOON__REPOSITORY_INFO

namespace parmoon
{
  /// @name information on the repository version and the build system
  /// @brief here some information from configure time (during a `cmake` run) is
  /// made available during compile and run time.
  /// @details These variables are declared to be extern here and defined in a
  /// file (ParMooN_repository_info.cpp) generated by the build system. This
  /// means source files which include this header file, do not need to be
  /// recompiled if the values of these variables change.
  //@{
  extern const char git_revision[];
  extern const char git_branch[];
  extern const bool git_local_changes;
  extern const char parallel_type[];
  extern const char build_type[];
  extern const char source_directory[];
  //@}
}

#endif // PARMOON__REPOSITORY_INFO
